### ISSUE TITLE
Peer review de Mercado Liebre

### ISSUE THREAD

**Issue by VeronicaBianchi** [TheMishi99/Mercado-Liebre#2]
Por empezar respecto a la estructura del sitio a visualizar contiene todos los elementos de cada sección.
Header: CUMPLE 
Main: CUMPLE 
Footer: CUMPLE

Cumple con todos los requisitos solicitados. 
 
El home es visualmente muy bueno y funcional. El código está bien identado y separa los estilos de acuerdo a cada página lo que hace más fácil su lectura. . Lo que considero a mejorar son los estilos y la estructura para la página de login y register para que estéticamente se aprecie mejor. El resto para mi está muy bien trabajado. 

FELICIDADES COMPAÑERO POR TU ESFUERZOO!! :)

**Comment by TheMishi99** [comment]
Issues corregidos!
